// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-bhaVPBgxGlwUsGK22hmWnA2r-mmRX8',
    appId: '1:527523362891:web:7ea033f82d0b755410b5ce',
    messagingSenderId: '527523362891',
    projectId: 'trainxercise-48fef',
    authDomain: 'trainxercise-48fef.firebaseapp.com',
    storageBucket: 'trainxercise-48fef.appspot.com',
    measurementId: 'G-3WBVZ2P0ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIVszJEbPRkgWF7Zi7MLdP_gVgesSGd4',
    appId: '1:527523362891:android:b6924f7487f5545210b5ce',
    messagingSenderId: '527523362891',
    projectId: 'trainxercise-48fef',
    storageBucket: 'trainxercise-48fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfINEofhnyRMBsZL3qL6VzQzeI3SVU5A4',
    appId: '1:527523362891:ios:930c98d42028aeb810b5ce',
    messagingSenderId: '527523362891',
    projectId: 'trainxercise-48fef',
    storageBucket: 'trainxercise-48fef.appspot.com',
    iosClientId: '527523362891-ssb6cglv4mkjihiutfgdq2ca0s9i9sos.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainxercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfINEofhnyRMBsZL3qL6VzQzeI3SVU5A4',
    appId: '1:527523362891:ios:014da26de634fe4210b5ce',
    messagingSenderId: '527523362891',
    projectId: 'trainxercise-48fef',
    storageBucket: 'trainxercise-48fef.appspot.com',
    iosClientId: '527523362891-sdbkfutubvoqt6qdut0e6cvo1aai0qpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainxercise.RunnerTests',
  );
}
